spring.datasource.url=jdbc:postgresql://192.168.10.24:${DB_EXPOSED_PORT:5434}/${POSTGRES_DB:interfisa_db}
spring.datasource.username=${POSTGRES_USER:app}
spring.datasource.password=${POSTGRES_PASSWORD:secret}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.h2.console.enabled=false
